#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

KEEP_ON_FAIL="0"
SUBDOMAIN=""
SKIP_BUILD="0"
IMAGE_TAG="gssh-e2e-runner:latest"

usage() {
  cat <<'EOF'
Usage: run-on-demand.sh [options]

Options:
  --subdomain <name>   Use a fixed subdomain instead of autogenerated one
  --keep-on-fail       Keep container + resources on failure for debugging
  --skip-build         Skip docker image build
  -h, --help           Show help

Environment overrides:
  GITSPACE_TOKEN       If set, used instead of keychain lookup
  SPRITES_TOKEN        If set, used instead of keychain lookup
  GITSPACE_API_URL     Optional API override passed through
EOF
}

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    printf "Missing required command: %s\n" "$1" >&2
    exit 1
  fi
}

resolve_secret_from_keychain() {
  local key="$1"
  (
    cd "$REPO_ROOT"
    bun -e 'const { getSecret } = await import("./src/utils/secrets.ts"); const key = process.argv[1] ?? ""; const value = await getSecret(key); if (!value) process.exit(1); process.stdout.write(value);' "$key"
  )
}

resolve_sprites_token_from_keychain() {
  (
    cd "$REPO_ROOT"
    bun -e 'const { getSpritesToken } = await import("./src/relay/control/provider-config.ts"); const value = await getSpritesToken(); if (!value) process.exit(1); process.stdout.write(value);'
  )
}

resolve_device_fingerprint() {
  (
    cd "$REPO_ROOT"
    bun -e 'const { getPublicKeyWithoutPassword } = await import("./src/core/identity.ts"); const identity = getPublicKeyWithoutPassword(); if (!identity?.signingPublicKey) process.exit(1); process.stdout.write(identity.signingPublicKey);'
  )
}

generate_subdomain() {
  local rand
  rand="$(bun -e 'process.stdout.write(Math.random().toString(36).slice(2, 8));')"
  printf "e2e-%s-%s" "$(date +%s | tail -c 5)" "$rand"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --keep-on-fail)
      KEEP_ON_FAIL="1"
      shift
      ;;
    --subdomain)
      if [[ $# -lt 2 ]]; then
        printf "--subdomain requires a value\n" >&2
        exit 1
      fi
      SUBDOMAIN="$2"
      shift 2
      ;;
    --skip-build)
      SKIP_BUILD="1"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      printf "Unknown argument: %s\n\n" "$1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

require_command docker
require_command bun

if [[ -z "$SUBDOMAIN" ]]; then
  SUBDOMAIN="$(generate_subdomain)"
fi

DEVICE_FINGERPRINT_VALUE="${E2E_DEVICE_FINGERPRINT:-}"
if [[ -z "$DEVICE_FINGERPRINT_VALUE" ]]; then
  if ! DEVICE_FINGERPRINT_VALUE="$(resolve_device_fingerprint)"; then
    printf "Could not resolve local device fingerprint (identity missing?).\n" >&2
    printf "Run: gssh user identity init\n" >&2
    exit 1
  fi
fi

GITSPACE_TOKEN_VALUE="${GITSPACE_TOKEN:-}"
if [[ -z "$GITSPACE_TOKEN_VALUE" ]]; then
  if ! GITSPACE_TOKEN_VALUE="$(resolve_secret_from_keychain 'GITSPACE_TOKEN')"; then
    printf "Could not resolve GITSPACE_TOKEN from env or keychain.\n" >&2
    exit 1
  fi
fi

SPRITES_TOKEN_VALUE="${SPRITES_TOKEN:-}"
if [[ -z "$SPRITES_TOKEN_VALUE" ]]; then
  if ! SPRITES_TOKEN_VALUE="$(resolve_sprites_token_from_keychain)"; then
    printf "Could not resolve SPRITES_TOKEN from env or keychain.\n" >&2
    exit 1
  fi
fi

if [[ "$SKIP_BUILD" != "1" ]]; then
  docker build -f "$REPO_ROOT/scripts/e2e/container/Dockerfile" -t "$IMAGE_TAG" "$REPO_ROOT"
fi

secret_env_file="$(mktemp "${TMPDIR:-/tmp}/gssh-e2e-secrets.XXXXXX")"
chmod 600 "$secret_env_file"
cat >"$secret_env_file" <<EOF
GITSPACE_TOKEN_INPUT=$GITSPACE_TOKEN_VALUE
SPRITES_TOKEN_INPUT=$SPRITES_TOKEN_VALUE
EOF
trap 'rm -f "$secret_env_file"' EXIT

container_suffix="$(date +%s)-$(bun -e 'process.stdout.write(Math.random().toString(36).slice(2, 8));')"
container_name="gssh-e2e-${container_suffix}"

docker_args=(
  run
  --name "$container_name"
  --env-file "$secret_env_file"
  -e "E2E_SUBDOMAIN=$SUBDOMAIN"
  -e "KEEP_ON_FAIL=$KEEP_ON_FAIL"
  -e "E2E_DEVICE_FINGERPRINT=$DEVICE_FINGERPRINT_VALUE"
)

if [[ -n "${GITSPACE_API_URL:-}" ]]; then
  docker_args+=( -e "GITSPACE_API_URL=${GITSPACE_API_URL}" )
fi

if [[ "$KEEP_ON_FAIL" != "1" ]]; then
  docker_args+=( --rm )
fi

docker_args+=( "$IMAGE_TAG" )

set +e
docker "${docker_args[@]}"
exit_code=$?
set -e

if [[ "$exit_code" -ne 0 ]]; then
  printf "\nE2E run failed (exit %s).\n" "$exit_code" >&2
  if [[ "$KEEP_ON_FAIL" == "1" ]]; then
    printf "Container kept for debugging: %s\n" "$container_name" >&2
    printf "Inspect logs: docker logs %s\n" "$container_name" >&2
    printf "Shell in:      docker exec -it %s bash\n" "$container_name" >&2
  fi
  exit "$exit_code"
fi

printf "\nE2E run succeeded for subdomain: %s\n" "$SUBDOMAIN"
