/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false` (hash: c3d4413ba0b5d90ac9e099f00cec52c7)
interface __BaseEnv_Env {
	DATA: R2Bucket;
	ASSETS: Fetcher;
	CF_ACCOUNT_ID: "2ed07d2f77ecb2aa43ca99a9c970597c";
	PLATFORM_URL: "https://platform.gssh.dev";
	ACCESS_TEAM_DOMAIN: "https://inkibra.cloudflareaccess.com";
	ACCESS_AUD: "b2e78441a0b1f9493647248fd9ae282982fdaff69fb118ff21a1ed1095679ec0";
	OPERATOR_EMAIL: "bradleat@inkibra.com";
	CREDENTIALS: DurableObjectNamespace<import("./src/index").CredentialVaultDO>;
	USER_STORAGE: DurableObjectNamespace /* UserStorageDO */;
	SPACE_AUTHORITY: DurableObjectNamespace /* SpaceAuthorityDO */;
	FLEET_CATALOG: DurableObjectNamespace /* FleetCatalogDO */;
	USER_SETTINGS: DurableObjectNamespace /* UserSettingsDO */;
	USER_HANDLES: DurableObjectNamespace /* HandleRegistryDO */;
	PROJECT_SECRETS: DurableObjectNamespace /* ProjectSecretsDO */;
	PROJECT_CRONS: DurableObjectNamespace /* ProjectCronsDO */;
	SPACE_CONTEXT: DurableObjectNamespace /* SpaceContextDO */;
	USER_SKILLS: DurableObjectNamespace /* UserSkillsDO */;
	USER_PROJECTS: DurableObjectNamespace /* UserProjectIndexDO */;
	PROJECT_AUTHORITY: DurableObjectNamespace /* ProjectAuthorityDO */;
	USER_MCP_CONNECTIONS: DurableObjectNamespace /* UserMcpConnectionsDO */;
	TENANT_RELEASES: DurableObjectNamespace<import("./src/index").TenantReleasesDO>;
	HOSTED_ROUTES: DurableObjectNamespace /* HostedRouteRegistryDO */;
	INVITES: DurableObjectNamespace /* InviteRegistryDO */;
	ACCOUNTS: DurableObjectNamespace /* AccountRegistryDO */;
	SANDBOX_PROVISIONER: Fetcher /* gitspace-sandbox-worker */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "CredentialVaultDO" | "UserStorageDO" | "SpaceAuthorityDO" | "FleetCatalogDO" | "UserSettingsDO" | "HandleRegistryDO" | "ProjectSecretsDO" | "ProjectCronsDO" | "SpaceContextDO" | "UserSkillsDO" | "UserProjectIndexDO" | "ProjectAuthorityDO" | "UserMcpConnectionsDO" | "TenantReleasesDO" | "HostedRouteRegistryDO" | "InviteRegistryDO" | "AccountRegistryDO";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CF_ACCOUNT_ID" | "PLATFORM_URL" | "ACCESS_TEAM_DOMAIN" | "ACCESS_AUD" | "OPERATOR_EMAIL">> {}
}
