// Untitled UI mapping for Fluid's named icon slots. Mirrors the docs site's
// own `untitleduiMap` (lib/docs/icon-map.tsx) so GitSpace renders the same
// glyphs the playground shows with the Untitled UI library selected.
import type { ComponentType } from 'react';
import { Pause, Play } from 'lucide-react';
import {
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Bell01,
  BookClosed,
  Brush01,
  Calendar,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronSelectorVertical,
  Circle,
  Clock,
  Copy01,
  CornerDownLeft,
  CornerDownRight,
  CpuChip01,
  DotsHorizontal,
  DotsVertical,
  Dropper,
  Folder,
  Globe01,
  Heart,
  Home01,
  Image01,
  Inbox01,
  LayoutLeft,
  LayoutRight,
  Lightbulb01,
  Link01,
  Loading01,
  Lock01,
  Mail01,
  Menu01,
  MessageCircle01,
  Monitor01,
  Moon01,
  Palette,
  Pencil01,
  Plus,
  RefreshCcw01,
  Rocket01,
  Scale01,
  SearchMd,
  Settings01,
  Shield01,
  SkipForward,
  Sliders01,
  Square,
  Star01,
  Sun,
  User01,
  Users01,
  XClose,
} from '@untitledui/icons';
import type { IconComponent, IconComponentProps, IconName } from './fluid-vendor/lib/icon-context.js';

type UntitledIcon = ComponentType<{ width?: number; height?: number; strokeWidth?: number; className?: string }>;

function untitledui(Icon: UntitledIcon): IconComponent {
  return function UntitledUiAdapter({ size, strokeWidth, className }: IconComponentProps) {
    return <Icon width={size} height={size} strokeWidth={strokeWidth} className={className} />;
  };
}

export const untitledIcons: Record<IconName, IconComponent> = {
  'chevron-right': untitledui(ChevronRight),
  'chevron-down': untitledui(ChevronDown),
  pipette: untitledui(Dropper),
  x: untitledui(XClose),
  copy: untitledui(Copy01),
  menu: untitledui(Menu01),
  dot: untitledui(Circle),
  monitor: untitledui(Monitor01),
  sun: untitledui(Sun),
  moon: untitledui(Moon01),
  'rectangle-horizontal': untitledui(Square),
  circle: untitledui(Circle),
  'square-library': untitledui(BookClosed),
  clock: untitledui(Clock),
  star: untitledui(Star01),
  settings: untitledui(Settings01),
  plus: untitledui(Plus),
  'arrow-left': untitledui(ArrowLeft),
  'arrow-right': untitledui(ArrowRight),
  'arrow-up': untitledui(ArrowUp),
  'arrow-down': untitledui(ArrowDown),
  search: untitledui(SearchMd),
  loader: untitledui(Loading01),
  users: untitledui(Users01),
  lock: untitledui(Lock01),
  mail: untitledui(Mail01),
  bell: untitledui(Bell01),
  shield: untitledui(Shield01),
  palette: untitledui(Palette),
  lightbulb: untitledui(Lightbulb01),
  rocket: untitledui(Rocket01),
  heart: untitledui(Heart),
  paintbrush: untitledui(Brush01),
  brain: untitledui(CpuChip01),
  globe: untitledui(Globe01),
  user: untitledui(User01),
  image: untitledui(Image01),
  link: untitledui(Link01),
  check: untitledui(Check),
  'rotate-ccw': untitledui(RefreshCcw01),
  play: Play,
  pause: Pause,
  home: untitledui(Home01),
  'message-circle': untitledui(MessageCircle01),
  inbox: untitledui(Inbox01),
  pencil: untitledui(Pencil01),
  scaling: untitledui(Scale01),
  'skip-forward': untitledui(SkipForward),
  'corner-down-right': untitledui(CornerDownRight),
  'corner-down-left': untitledui(CornerDownLeft),
  'panel-left': untitledui(LayoutLeft),
  'panel-right': untitledui(LayoutRight),
  'chevrons-up-down': untitledui(ChevronSelectorVertical),
  'more-horizontal': untitledui(DotsHorizontal),
  'more-vertical': untitledui(DotsVertical),
  calendar: untitledui(Calendar),
  folder: untitledui(Folder),
  'sliders-horizontal': untitledui(Sliders01),
};
