import type { AnyProcedureContract } from 'result-rpc';
import type { gitspaceContract } from './rpc-contract.js';

type ProcedurePaths<T> = {
  [K in keyof T & string]: T[K] extends AnyProcedureContract ? K : `${K}.${ProcedurePaths<T[K]>}`;
}[keyof T & string];

export type GitSpaceProcedurePath = ProcedurePaths<typeof gitspaceContract.record>;
export type RpcAuthority = 'cloud' | 'machine';

/** Every public procedure has one authority. Adding a contract requires an explicit
 * routing decision here. Cloud procedures may dispatch effects to an explicitly
 * named cache, but no public procedure follows a legacy holder or an online default. */
export const ACCOUNT_RPC_AUTHORITY = {
  'runtime.snapshot': 'cloud',
  'runtime.draft': 'cloud',
  'runtime.submit': 'cloud',
  'runtime.cancel': 'cloud',
  'runtime.answer': 'cloud',
  'runtime.browserTrust': 'cloud',
  'runtime.watch': 'cloud',
  'runtime.session': 'cloud',
  'runtime.services': 'cloud',
  'runtime.executionMachine': 'cloud',
  'runtime.qa': 'cloud',
  'runtime.attachment.request': 'cloud',
  'runtime.attachment.cache.request': 'cloud',
  'runtime.attachment.action': 'cloud',
  'runtime.attachment.detach': 'cloud',
  'machines': 'cloud',
  'machine.events': 'cloud',
  'machine.updateNotes': 'cloud',
  'machine.createSandbox': 'cloud',
  'machine.sleep': 'cloud',
  'machine.resume': 'cloud',
  'machine.destroy': 'cloud',
  'machine.image.list': 'cloud',
  'machine.image.events': 'cloud',
  'machine.image.set': 'cloud',
  'machine.image.retry': 'cloud',
  'machine.image.cancel': 'cloud',
  'machine.image.recover': 'cloud',
  'machine.image.defaults.get': 'cloud',
  'machine.image.defaults.set': 'cloud',
  'settings.get': 'cloud',
  'settings.git.get': 'cloud',
  'settings.update': 'cloud',
  'settings.reserveHandle': 'cloud',
  'settings.runtime.get': 'cloud',
  'settings.runtime.set': 'cloud',
  'settings.events': 'cloud',
  'inference.list': 'cloud',
  'inference.create': 'cloud',
  'inference.update': 'cloud',
  'inference.delete': 'cloud',
  'inference.assign': 'cloud',
  'inference.events': 'cloud',
  'providers.list': 'cloud',
  'providers.login.start': 'cloud',
  'providers.login.events': 'cloud',
  'providers.login.respond': 'cloud',
  'providers.login.cancel': 'cloud',
  'providers.logout': 'cloud',
  'providers.apiKey.set': 'cloud',
  'providers.usage': 'cloud',
  'providers.models': 'cloud',
  'devices.list': 'cloud',
  'devices.revoke': 'cloud',
  'deployment.status': 'cloud',
  'deployment.launch': 'machine',
  'deployment.revert': 'cloud',
  'secrets.list': 'cloud',
  'secrets.put': 'cloud',
  'secrets.delete': 'cloud',
  'secrets.account.list': 'cloud',
  'secrets.account.put': 'cloud',
  'secrets.account.delete': 'cloud',
  'secrets.account.grant': 'cloud',
  'secrets.account.revoke': 'cloud',
  'configuration.values.get': 'cloud',
  'configuration.values.put': 'cloud',
  'configuration.values.delete': 'cloud',
  'environment.events': 'cloud',
  'environment.get': 'cloud',
  'environment.putBundle': 'cloud',
  'environment.setProfile': 'cloud',
  'environment.putValue': 'cloud',
  'environment.deleteValue': 'cloud',
  'environment.approve': 'cloud',
  'environment.revokeApproval': 'cloud',
  'environment.runChecks': 'cloud',
  'environment.runPhase': 'cloud',
  'environment.cancelRun': 'cloud',
  'environment.recoverRun': 'cloud',
  'environment.runLog': 'cloud',
  'mcp.connections.list': 'cloud',
  'mcp.connections.create': 'cloud',
  'mcp.connections.update': 'cloud',
  'mcp.connections.delete': 'cloud',
  'mcp.connections.status': 'cloud',
  'mcp.composio.setup.get': 'cloud',
  'mcp.composio.setup.put': 'cloud',
  'mcp.composio.setup.delete': 'cloud',
  'mcp.composio.catalog': 'cloud',
  'mcp.composio.authorize': 'cloud',
  'mcp.composio.refresh': 'cloud',
  'mcp.composio.tools': 'cloud',
  'mcp.composio.updateTools': 'cloud',
  'mcp.composio.disconnect': 'cloud',
  'mcp.grants.list': 'cloud',
  'mcp.grants.put': 'cloud',
  'mcp.grants.delete': 'cloud',
  'mcp.discover': 'cloud',
  'crons.list': 'cloud',
  'crons.create': 'cloud',
  'crons.update': 'cloud',
  'crons.delete': 'cloud',
  'crons.runNow': 'cloud',
  'crons.cancelRun': 'cloud',
  'crons.history': 'cloud',
  'skills.list': 'cloud',
  'skills.update': 'cloud',
  'inspector.view': 'cloud',
  'inspector.transcript': 'cloud',
  'inspector.transcriptPage': 'cloud',
  'inspector.transcriptContent': 'cloud',
  'inspector.availability': 'cloud',
  'inspector.overview': 'cloud',
  'inspector.goal.put': 'cloud',
  'inspector.goal.attachEvidence': 'cloud',
  'inspector.workflow.put': 'cloud',
  'inspector.workflow.waiveGate': 'cloud',
  'inspector.rubric.put': 'cloud',
  'inspector.rubric.appendJudgment': 'cloud',
  'inspector.journal.list': 'cloud',
  'inspector.journal.startPhase': 'cloud',
  'inspector.journal.endPhase': 'cloud',
  'inspector.journal.append': 'cloud',
  'inspector.guide.put': 'cloud',
  'inspector.guide.analyze': 'cloud',
  'inspector.guide.submit': 'cloud',
  'inspector.guide.markSectionRead': 'cloud',
  'inspector.guide.setApproval': 'cloud',
  'inspector.review.list': 'cloud',
  'inspector.review.create': 'cloud',
  'inspector.review.reply': 'cloud',
  'inspector.review.resolve': 'cloud',
  'inspector.repository.tree': 'cloud',
  'inspector.repository.treePage': 'cloud',
  'inspector.repository.status': 'cloud',
  'inspector.repository.file': 'cloud',
  'inspector.repository.diff': 'cloud',
  'inspector.resources.read': 'cloud',
  'inspector.resources.readPage': 'cloud',
  'inspector.artifacts.read': 'cloud',
  'inspector.artifacts.write': 'cloud',
  'inspector.artifacts.uploadBegin': 'cloud',
  'inspector.artifacts.uploadChunk': 'cloud',
  'inspector.artifacts.uploadCommit': 'cloud',
  'inspector.artifacts.uploadAbort': 'cloud',
  'inspector.artifacts.readPage': 'cloud',
  'inspector.artifacts.list': 'cloud',
  'inspector.artifacts.copyToProject': 'cloud',
  'inspector.artifacts.shares.list': 'cloud',
  'inspector.artifacts.shares.create': 'cloud',
  'inspector.artifacts.shares.revoke': 'cloud',
  'inspector.services.list': 'cloud',
  'inspector.services.start': 'cloud',
  'inspector.services.stop': 'cloud',
  'project.events': 'cloud',
  'project.directoryEvents': 'cloud',
  'project.list': 'cloud',
  'project.create': 'cloud',
  'project.ensureGitSpace': 'cloud',
  'project.archive': 'cloud',
  'project.restore': 'cloud',
  'project.setBaseBranch': 'cloud',
  'project.delete': 'cloud',
  'space.view': 'cloud',
  'space.events': 'cloud',
  'workspace.create': 'cloud',
  'workspace.retryCreate': 'cloud',
  'workspace.archive': 'cloud',
  'workspace.restore': 'cloud',
  'workspace.delete': 'cloud',
  'workspace.setRelations': 'cloud',
  'workspace.stackStatus': 'cloud',
  'terminals.events': 'machine',
  'terminals.live': 'machine',
  'terminals.list': 'machine',
  'terminals.create': 'machine',
  'terminals.read': 'machine',
  'terminals.send': 'machine',
  'terminals.stop': 'machine',
  'incidents.record': 'cloud',
} as const satisfies Readonly<Record<GitSpaceProcedurePath, RpcAuthority>>;

const authorityByPath: Readonly<Record<string, RpcAuthority | undefined>> = ACCOUNT_RPC_AUTHORITY;

/** Unknown paths are not machine work. Callers must reject an absent authority. */
export function accountRpcAuthority(path: string): RpcAuthority | undefined {
  return Object.hasOwn(authorityByPath, path) ? authorityByPath[path] : undefined;
}

export type RpcCallTarget =
  | { kind: 'terminal'; spaceId: string; machineId: string }
  | { kind: 'machine'; machineId: string };

export function rpcCallTarget(path: string, input: unknown): RpcCallTarget | null {
  if (accountRpcAuthority(path) !== 'machine' || !input || typeof input !== 'object') return null;
  if (!('machineId' in input) || typeof input.machineId !== 'string' || !input.machineId) return null;
  if (path.startsWith('terminals.')) {
    return 'spaceId' in input && typeof input.spaceId === 'string' && input.spaceId
      ? { kind: 'terminal', spaceId: input.spaceId, machineId: input.machineId }
      : null;
  }
  return { kind: 'machine', machineId: input.machineId };
}
