/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false` (hash: 7c79fe28b600e6a255cf07471c068eb3)
interface __BaseEnv_Env {
	DISPATCHER: DispatchNamespace;
	TENANT_HOST_SUFFIX: "-relay-spike.gssh.dev";
	DEFAULT_CPU_MS: 50;
	DEFAULT_SUBREQUESTS: 20;
	ADMIN_PUBLIC_KEY: "vOSduG2Ge02PoTK0oGKKFODyStGjBO46mv9TQXdRmLA=";
	ADMIN_AUTH_MAX_SKEW_MS: 60000;
	DISPATCH_RESERVATION_MICROS: 100;
	DISPATCH_SETTLEMENT_MICROS: 1;
	RESERVATION_TTL_MS: 30000;
	CREDITS: DurableObjectNamespace<import("./src/index").CreditLedgerDO>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "CreditLedgerDO";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TENANT_HOST_SUFFIX" | "DEFAULT_CPU_MS" | "DEFAULT_SUBREQUESTS" | "ADMIN_PUBLIC_KEY" | "ADMIN_AUTH_MAX_SKEW_MS" | "DISPATCH_RESERVATION_MICROS" | "DISPATCH_SETTLEMENT_MICROS" | "RESERVATION_TTL_MS">> {}
}
