/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false` (hash: 3a828cad7fdc51f6561b82ca7c2b7299)
interface __BaseEnv_Env {
	DISPATCHER: DispatchNamespace;
	TENANT_HOST_SUFFIX: "-relay-spike.gssh.dev";
	DEFAULT_CPU_MS: 50;
	DEFAULT_SUBREQUESTS: 20;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TENANT_HOST_SUFFIX" | "DEFAULT_CPU_MS" | "DEFAULT_SUBREQUESTS">> {}
}
