/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false` (hash: 52dc93d6e4c4fe279f1d6f438ef9a006)
interface __BaseEnv_Env {
	RELEASES: R2Bucket;
	DATA: R2Bucket;
	DISPATCHER: DispatchNamespace;
	TENANT_HOST_SUFFIX: ".gssh.dev";
	OPERATOR_URL: string;
	DEFAULT_CPU_MS: 50;
	DEFAULT_SUBREQUESTS: 20;
	ADMIN_PUBLIC_KEY: "vOSduG2Ge02PoTK0oGKKFODyStGjBO46mv9TQXdRmLA=";
	ADMIN_AUTH_MAX_SKEW_MS: 60000;
	DISPATCH_RESERVATION_MICROS: 100;
	DISPATCH_SETTLEMENT_MICROS: 1;
	DEPLOY_SETTLEMENT_MICROS: 1000;
	DEPLOY_PROBE_DELAY_MS: 2000;
	RESERVATION_TTL_MS: 30000;
	DISPATCH_NAMESPACE: "gitspace-relays";
	CF_ACCOUNT_ID: "2ed07d2f77ecb2aa43ca99a9c970597c";
	CREDITS: DurableObjectNamespace<import("./src/index").CreditLedgerDO>;
	DEPLOYMENTS: DurableObjectNamespace<import("./src/index").TenantDeploymentsDO>;
	TENANT_CONTROL: DurableObjectNamespace<import("./src/index").TenantControlDO>;
	AUTH: Fetcher /* gitspace-auth */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "CreditLedgerDO" | "TenantDeploymentsDO" | "TenantControlDO";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TENANT_HOST_SUFFIX" | "DEFAULT_CPU_MS" | "DEFAULT_SUBREQUESTS" | "ADMIN_PUBLIC_KEY" | "ADMIN_AUTH_MAX_SKEW_MS" | "DISPATCH_RESERVATION_MICROS" | "DISPATCH_SETTLEMENT_MICROS" | "DEPLOY_SETTLEMENT_MICROS" | "DEPLOY_PROBE_DELAY_MS" | "RESERVATION_TTL_MS" | "DISPATCH_NAMESPACE" | "CF_ACCOUNT_ID">> {}
}
