/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false` (hash: 63cf88fda4227ba5b5d8684099998fa4)
interface __BaseEnv_Env {
	DATA: R2Bucket;
	CF_ACCOUNT_ID: "configure-at-deploy";
	R2_PARENT_ACCESS_KEY_ID: "configure-at-deploy";
	GITSPACE_OMP_BROKER_TOKEN: "configure-at-deploy";
	PLATFORM_URL: "";
	PLATFORM_TENANT: "";
	CREDENTIALS: DurableObjectNamespace<import("./src/index").CredentialVaultDO>;
	USER_STORAGE: DurableObjectNamespace /* UserStorageDO */;
	SPACE_AUTHORITY: DurableObjectNamespace /* SpaceAuthorityDO */;
	FLEET_CATALOG: DurableObjectNamespace /* FleetCatalogDO */;
	USER_SETTINGS: DurableObjectNamespace /* UserSettingsDO */;
	USER_HANDLES: DurableObjectNamespace /* HandleRegistryDO */;
	PROJECT_SECRETS: DurableObjectNamespace /* ProjectSecretsDO */;
	PROJECT_CRONS: DurableObjectNamespace /* ProjectCronsDO */;
	SPACE_CONTEXT: DurableObjectNamespace /* SpaceContextDO */;
	USER_SKILLS: DurableObjectNamespace /* UserSkillsDO */;
	USER_PROJECTS: DurableObjectNamespace /* UserProjectIndexDO */;
	PROJECT_AUTHORITY: DurableObjectNamespace /* ProjectAuthorityDO */;
	USER_MCP_CONNECTIONS: DurableObjectNamespace /* UserMcpConnectionsDO */;
	TENANT_RELEASES: DurableObjectNamespace /* TenantReleasesDO */;
	SANDBOX_PROVISIONER: Fetcher /* gitspace-sandbox-worker */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "CredentialVaultDO" | "UserStorageDO" | "SpaceAuthorityDO" | "FleetCatalogDO" | "UserSettingsDO" | "HandleRegistryDO" | "ProjectSecretsDO" | "ProjectCronsDO" | "SpaceContextDO" | "UserSkillsDO" | "UserProjectIndexDO" | "ProjectAuthorityDO" | "UserMcpConnectionsDO" | "TenantReleasesDO";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CF_ACCOUNT_ID" | "R2_PARENT_ACCESS_KEY_ID" | "GITSPACE_OMP_BROKER_TOKEN" | "PLATFORM_URL" | "PLATFORM_TENANT">> {}
}
