import React from 'react';
import {
  AbsoluteFill,
  Audio,
  Sequence,
  staticFile,
  useCurrentFrame,
  interpolate,
  Easing,
} from 'remotion';
import { loadFont } from '@remotion/google-fonts/JetBrainsMono';
// NOTE: no VO track yet — the real recording lands here later.
import { T } from '../../lib/theme';
import { TL, DECK, ACTS } from './timeline';
import { ChainBoard } from './scenes/ChainBoard';
import { MorningOps } from './scenes/MorningOps';
import { Deck, EndCard, TAGLINE, STINGER } from './Deck';
import { KineticCaptions, type CapLine } from '../../lib/Captions';
import { FaultyTerminalFrame } from '../../lib/FaultyTerminalFrame';
import { ParticleScrollFrame } from '../../lib/ParticleScrollFrame';
import { BendFrame } from '../../lib/BendFrame';
import { Cursor } from '../../lib/ui';

loadFont();

const P = DECK.matchCut; // product-local offset (5s dust intro)
const CAP_SHIFT = 90; // captions live in (global − 90), same convention as ep02
const ease = Easing.inOut(Easing.cubic);
const clamp = { extrapolateLeft: 'clamp', extrapolateRight: 'clamp' } as const;

const A = T.waiting; // agent — the PR byline's blue
const G = T.accent; // the green things: beat badges, ✓ reviewed
const D = T.error; // the lie: alphabetical order's red dependency
const AM = T.needsInput; // the journal card's amber

/** Frames where typed() reveals a new character (mirrors ui.typed math). */
const typingFrames = (start: number, cps: number, chars: number): number[] => {
  const frames: number[] = [];
  let prev = 0;
  for (let f = start; prev < chars && f < start + 400; f++) {
    const n = Math.min(chars, Math.max(0, Math.floor((f - start) * cps)));
    if (n > prev) frames.push(f);
    prev = n;
  }
  return frames;
};
const everyThird = (frames: number[]): number[] =>
  frames.filter((_, i) => i % 3 === 0 || i === frames.length - 1);
const TAG_KEYS = everyThird(typingFrames(DECK.tagType, 1.35, TAGLINE.length));
const STING_KEYS = everyThird(typingFrames(DECK.stingerType, 1.35, STINGER.length));

/**
 * Captions generated by the ep04 prosody solver (/tmp/solve04.mjs +
 * /tmp/gen04.mjs). Past tense while the chain ships, present from "merge is
 * the midpoint". Colour only names what is on screen — including `done.` in
 * green, which is the false green this episode exists to correct.
 */
const MAIN_CAPTIONS: CapLine[] = [
  {
    // the four-goal track; `chain.` green — the merged badges are
    y: 872, size: 44, out: 200,
    words: [
      { w: 'Four', at: 89 }, { w: 'goals,', at: 97 }, { w: 'one', at: 112 }, { w: 'chain.', at: 120, color: G },
      { w: 'They', at: 140 }, { w: 'shipped', at: 148 }, { w: 'in', at: 161 }, { w: 'order.', at: 169 },
    ],
  },
  {
    // reacting to the ship: workspace out, next goal binds
    y: 872, size: 46, out: 322,
    words: [
      { w: 'Workspaces', at: 226 }, { w: 'came', at: 244 }, { w: 'and', at: 252 }, { w: 'went.', at: 260 },
      { w: 'The', at: 280 }, { w: 'plan', at: 288 }, { w: 'held.', at: 296 },
    ],
  },
  {
    // `done.` is green because the board is — the FALSE green, deliberately
    y: 872, size: 46, out: 454,
    words: [
      { w: 'The', at: 348 }, { w: 'last', at: 356 }, { w: 'goal', at: 364 }, { w: 'merged.', at: 372 },
      { w: 'Everything', at: 397 }, { w: 'said', at: 420 }, { w: 'done.', at: 428, color: G },
    ],
  },
  {
    // the turn — opens ON the bend. The leaned-on word.
    y: 866, size: 46, out: 543,
    words: [
      { w: 'But', at: 480 }, { w: 'merge', at: 488 }, { w: 'is', at: 496 }, { w: 'the', at: 504 },
      { w: 'midpoint.', at: 512, underline: true },
    ],
  },
  {
    // the cron fires unattended (no cursor: that is the point)
    y: 872, size: 42, out: 791,
    words: [
      { w: 'The', at: 663 }, { w: 'goal', at: 671 }, { w: 'left', at: 679 }, { w: 'a', at: 687 },
      { w: 'dashboard', at: 695 }, { w: 'behind.', at: 708 }, { w: 'A', at: 733 }, { w: 'cron', at: 741 },
      { w: 'keeps', at: 749 }, { w: 'it', at: 757 }, { w: 'fresh.', at: 765 },
    ],
  },
  {
    // `the line.` amber — the rubric subline under the amber tile
    y: 872, size: 46, out: 921,
    words: [
      { w: 'Day', at: 817 }, { w: 'two.', at: 825 }, { w: 'The', at: 845 }, { w: 'error', at: 853 },
      { w: 'rate', at: 866 }, { w: 'crosses', at: 874 }, { w: 'the', at: 887 }, { w: 'line.', at: 895, color: AM },
    ],
  },
  {
    // `rubric`/`reopens` amber — the reopened card is on screen
    y: 872, size: 46, out: 1036,
    words: [
      { w: 'The', at: 947 }, { w: 'rubric', at: 955, color: AM }, { w: 'that', at: 968 }, { w: 'shipped', at: 976 },
      { w: 'it', at: 989 }, { w: 'reopens', at: 997, color: AM }, { w: 'it.', at: 1010 },
    ],
  },
  {
    // the fleet strip: a reopened goal is just a new amber
    y: 872, size: 44, out: 1167,
    words: [
      { w: 'And', at: 1062 }, { w: 'I', at: 1070 }, { w: 'already', at: 1078 }, { w: 'know', at: 1096 },
      { w: 'what', at: 1104 }, { w: 'to', at: 1112 }, { w: 'do', at: 1120 }, { w: 'with', at: 1128 },
      { w: 'ambers.', at: 1136, color: AM },
    ],
  },
];

const VO_SEGMENTS: Array<[number, number]> = [
  [89, 194], [226, 316], [348, 448], [480, 537], [663, 785], [817, 915], [947, 1030], [1062, 1161],
];
const padDuck = (f: number): number => {
  for (const [a, b] of VO_SEGMENTS) {
    if (f >= a - 10 && f <= b + 16) {
      const in_ = Math.min(1, Math.max(0, (f - (a - 10)) / 10));
      const out_ = Math.min(1, Math.max(0, ((b + 16) - f) / 16));
      return 0.85 - 0.22 * Math.min(in_, out_);
    }
  }
  return 0.85;
};

/** The turn between pages and story — the one bend in the film. */
const TURN = {
  zone: 620,
  angle: 86,
  rounding: 260,
  perspective: 900,
  direction: 'in',
  ease: 620,
  smoothing: 0,
  transparent: true,
  top: true,
  bottom: true,
  tumble: 0,
  tilt: 0,
} as const;

/** Fine dark grain for the ending — the type erodes, not explodes. */
const SAND_OUT = {
  band: 700,
  density: 2.2,
  size: 1.5,
  spread: 210,
  gravity: 0.45,
  drift: 1,
  swirl: 150,
  stagger: 0.6,
  fade: 0.9,
  settle: 0.3,
  smoothing: 0,
  transparent: true,
} as const;

/** The product story, in product-local frames (pf). */
const Product: React.FC<{ pf: number }> = ({ pf }) => {
  const turning = pf >= TL.openSlideStart && pf < TL.openSlideEnd;
  const turn = interpolate(pf, [TL.openSlideStart, TL.openSlideEnd], [0, 1], { ...clamp, easing: ease });
  const showChain = pf < TL.openSlideStart;
  const showOps = pf >= TL.openSlideEnd;

  // the human's hand: cursor + click punch on the two acts only (ep01's envelope)
  let punch = 0;
  let punchAt = { x: 960, y: 540 };
  let cursorOp = 0;
  let cx = 960;
  let cy = 540;
  let click = 0;
  for (let i = 0; i < ACTS.length; i++) {
    const a = ACTS[i]!;
    const d = pf - a.at;
    if (d >= -26 && d <= 26) {
      const from = i > 0 ? ACTS[i - 1]! : { x: 1480, y: 320 };
      const travel = interpolate(pf, [a.at - 26, a.at - 2], [0, 1], { ...clamp, easing: ease });
      cx = from.x + (a.x - from.x) * travel;
      cy = from.y + (a.y - from.y) * travel;
      cursorOp =
        interpolate(pf, [a.at - 26, a.at - 18], [0, 1], clamp) *
        interpolate(pf, [a.at + 12, a.at + 24], [1, 0], clamp);
      click = interpolate(pf, [a.at, a.at + 12], [1, 0], clamp);
    }
    if (d >= 0 && d <= 28) {
      punch =
        d < 3 ? Easing.out(Easing.cubic)(d / 3)
        : d < 8 ? 1
        : 1 - Easing.inOut(Easing.cubic)((d - 8) / 20);
      punchAt = { x: a.x, y: a.y };
    }
  }
  const punchScale = 1 + 0.028 * punch;

  return (
    <AbsoluteFill
      style={{
        background: T.bg,
        transform: `scale(${punchScale})`,
        transformOrigin: `${punchAt.x}px ${punchAt.y}px`,
      }}
    >
      {/* the site's hero field — 0.22, the measured video value, not the web's 0.12 */}
      <FaultyTerminalFrame width={1920} height={1080} opacity={0.22} />

      {showChain && <ChainBoard frame={pf} />}

      {/* THE TURN — pages fold away, the story unfolds. One sheet. */}
      {turning && (
        <BendFrame position={turn} options={TURN}>
          <ChainBoard frame={pf} />
          <MorningOps frame={pf} />
        </BendFrame>
      )}

      {showOps && <MorningOps frame={pf} />}

      {cursorOp > 0.001 && (
        <div style={{ opacity: cursorOp }}>
          <Cursor x={cx} y={cy} click={click} />
        </div>
      )}
    </AbsoluteFill>
  );
};

export const ShippedIsntDone: React.FC = () => {
  const frame = useCurrentFrame();
  const pf = frame - P;
  const inDeck = frame < P || frame >= DECK.outStart;
  const sanding = frame >= DECK.sandStart;
  const product = <Product pf={pf} />;

  return (
    <AbsoluteFill style={{ background: T.bg }}>
      {/* ── soundtrack ── */}
      <Audio
        src={staticFile('audio/pad-long.wav')}
        volume={(f) => padDuck(f - CAP_SHIFT) * interpolate(f, [DECK.total - 70, DECK.total - 8], [1, 0], clamp)}
      />
      <Audio src={staticFile('audio/riser.wav')} volume={0.8} />
      <Sequence from={DECK.select}>
        <Audio src={staticFile('audio/thunk.wav')} volume={0.8} />
      </Sequence>
      {/* the FALSE green — the chain completes (bloom, deliberately) */}
      <Sequence from={TL.allGreen + P}>
        <Audio src={staticFile('audio/bloom-flags.wav')} volume={0.65} />
      </Sequence>
      {/* day two — the error rate crosses the rubric line */}
      <Sequence from={TL.amber + P}>
        <Audio src={staticFile('audio/droplet-amber.wav')} volume={0.75} />
      </Sequence>
      {/* the shipped goal reopens */}
      <Sequence from={TL.reopen + P}>
        <Audio src={staticFile('audio/thunk.wav')} volume={0.7} />
      </Sequence>
      {/* the two clicks */}
      {ACTS.map((a) => (
        <Sequence key={`click-${a.at}`} from={a.at + P}>
          <Audio src={staticFile('audio/click.wav')} volume={0.75} />
        </Sequence>
      ))}
      {/* the turn */}
      <Sequence from={TL.openSlideStart + P}>
        <Audio src={staticFile('audio/whoosh.wav')} volume={0.55} />
      </Sequence>
      {/* the third ship lands mid-chain */}
      <Sequence from={TL.ship3 + P}>
        <Audio src={staticFile('audio/bloom-docs.wav')} volume={0.55} />
      </Sequence>
      {/* the fleet strip settles it */}
      <Sequence from={TL.fleet + P}>
        <Audio src={staticFile('audio/sparkle.wav')} volume={0.55} />
      </Sequence>
      <Sequence from={DECK.outStart}>
        <Audio src={staticFile('audio/whoosh.wav')} volume={0.55} />
      </Sequence>
      <Sequence from={DECK.deckBack}>
        <Audio src={staticFile('audio/sparkle.wav')} volume={0.5} />
      </Sequence>
      {[...TAG_KEYS, ...STING_KEYS].map((at, i) => (
        <Sequence key={`tagkey-${at}-${i}`} from={at}>
          <Audio src={staticFile(`audio/key-${((i + 2) % 4) + 1}.wav`)} volume={0.26} />
        </Sequence>
      ))}

      {/* ── one snippet in a deck of snippets ── */}
      {inDeck ? <Deck frame={frame} hideType={sanding}>{product}</Deck> : product}

      {/* ── the ending: the type erodes into sand ── */}
      {sanding && (
        <>
          <AbsoluteFill
            style={{ background: '#000', opacity: interpolate(frame, [DECK.sandStart, DECK.sandStart + 30], [0, 1], clamp) }}
          />
          <ParticleScrollFrame
            progress={interpolate(frame, [DECK.sandStart, DECK.sandEnd], [1, 0], { ...clamp, easing: Easing.in(Easing.quad) })}
            options={SAND_OUT}
          >
            <EndCard frame={frame} />
          </ParticleScrollFrame>
        </>
      )}

      {/* ── VO captions (placeholder timings; retime to the recording) ── */}
      <KineticCaptions frame={frame - CAP_SHIFT} lines={MAIN_CAPTIONS} />
    </AbsoluteFill>
  );
};
