import { ArrowLeft, Bot, Check, ChevronRight, Chrome, Copy, ExternalLink, GitBranch, Globe2, Laptop, Monitor, Puzzle, Radio, Server, Settings2, ShieldCheck, TestTube2, UserRound, Wifi } from 'lucide-react';
import { useState } from 'react';
import { createRoot } from 'react-dom/client';
import '../src/styles.css';
import './browser-relay-preview.css';

type Step = 0 | 1 | 2 | 3 | 4;
const navigation = [{ label: 'Profile', Icon: UserRound }, { label: 'OMP', Icon: Bot }, { label: 'Git', Icon: GitBranch }, { label: 'Machines', Icon: Server }, { label: 'Domains', Icon: Globe2 }, { label: 'Defaults', Icon: Settings2 }];
function Status({ ready, children }: { ready?: boolean; children: string }) { return <span className="relay-status" data-ready={ready || undefined}><i />{children}</span>; }
function Progress({ step }: { step: Step }) { return <div className="relay-progress" aria-label={`Step ${step} of 3`}>{[1,2,3].map((value) => <i key={value} data-done={step >= value || undefined} />)}</div>; }
function BrowserRelaySetup({ step, setStep, onDone }: { step: Step; setStep: (step: Step) => void; onDone: () => void }) {
  const [prepared, setPrepared] = useState(false);
  const [extensionsOpened, setExtensionsOpened] = useState(false);
  const [developerMode, setDeveloperMode] = useState(false);
  const [loaded, setLoaded] = useState(false);
  const [badgeOn, setBadgeOn] = useState(false);
  const [tested, setTested] = useState(false);
  if (step !== 1) return null;
  const readyToTest = prepared && extensionsOpened && developerMode && loaded && badgeOn;
  return <section className="relay-setup relay-checklist-setup">
    <header className="relay-setup-header"><div><span>Browser Relay setup</span><h2>Set up Chrome on Darktop</h2><p>Complete this checklist once for the Chrome profile you want GitSpace to control. GitSpace handles the machine-side preparation; Chrome keeps the extension installation under your control.</p></div></header>
    <div className="relay-install-facts"><div><span>Extension directory</span><code>~/gitspace/.browser-relay/extension</code></div><div><span>Local relay</span><code>http://127.0.0.1:9224</code></div></div>
    <div className="relay-command"><span><strong>Command fallback · Darktop WSL2</strong><small>The Prepare button runs this same machine-local operation.</small></span><code>gssh machine browser-relay setup</code><button className="relay-button" aria-label="Copy Browser Relay setup command"><Copy size={13} />Copy</button></div>
    <div className="relay-checklist">
      <div className="relay-checklist-item" data-done={prepared || undefined}><span>1</span><div><strong>Prepare Browser Relay on Darktop</strong><small>Writes GitSpace’s bundled extension files and enables the internal browser relay runtime.</small></div>{prepared ? <em><Check size={14} />Done</em> : <button className="relay-button primary" onClick={() => setPrepared(true)}>Prepare</button>}</div>
      <div className="relay-checklist-item" data-done={extensionsOpened || undefined}><span>2</span><div><strong>Open Chrome extensions</strong><small>Open <code>chrome://extensions</code> in Chrome on Darktop.</small></div>{extensionsOpened ? <em><Check size={14} />Opened</em> : <button className="relay-button" disabled={!prepared} onClick={() => setExtensionsOpened(true)}>Open page</button>}</div>
      <label className="relay-checklist-item" data-done={developerMode || undefined}><span>3</span><div><strong>Enable Developer mode</strong><small>Use the switch in the top-right of Chrome’s extensions page.</small></div><input type="checkbox" checked={developerMode} disabled={!extensionsOpened} onChange={(event) => setDeveloperMode(event.currentTarget.checked)} /></label>
      <label className="relay-checklist-item" data-done={loaded || undefined}><span>4</span><div><strong>Load the unpacked extension</strong><small>Click <b>Load unpacked</b> and choose the Chrome-accessible folder below.</small><code className="relay-checklist-path">\\\\wsl.localhost\\Ubuntu\\home\\bradleat\\gitspace\\.browser-relay\\extension</code></div><input type="checkbox" checked={loaded} disabled={!developerMode} onChange={(event) => setLoaded(event.currentTarget.checked)} /></label>
      <label className="relay-checklist-item" data-done={badgeOn || undefined}><span>5</span><div><strong>Confirm the extension badge says “on”</strong><small>The badge changes after the extension reaches GitSpace’s local relay.</small></div><input type="checkbox" checked={badgeOn} disabled={!loaded} onChange={(event) => setBadgeOn(event.currentTarget.checked)} /></label>
      <div className="relay-checklist-item" data-done={tested || undefined}><span>6</span><div><strong>Test Browser Relay</strong><small>{tested ? 'GitSpace attached to and released a test tab successfully.' : 'Checks the localhost relay, extension bridge, and controlled-tab path.'}</small></div>{tested ? <em><Check size={14} />Passed</em> : <button className="relay-button" disabled={!readyToTest} onClick={() => setTested(true)}><TestTube2 size={14} />Run test</button>}</div>
    </div>
    <div className="relay-security-note"><strong>Browser access is never ambient.</strong> This checklist only connects Chrome to Browser Relay on the same computer. GitSpace still requires a separate, explicit approval before an agent receives a tab lease.</div>
    <footer><button className="relay-button" onClick={() => setStep(0)}>Cancel</button><button className="relay-button primary" disabled={!tested} onClick={onDone}><Check size={14} />Finish setup</button></footer>
  </section>;
}
function MachineSettingsMock() {
  const [step, setStep] = useState<Step>(0);
  const ready = step === 4;
  return <div className="settings-gallery"><div className="sg-settings" data-detail><nav><button className="sg-back"><ArrowLeft size={14} />Back to workspace</button>{navigation.map(({ label, Icon }) => <button key={label} data-active={label === 'Machines' || undefined}><Icon size={14} /><span>{label}</span><ChevronRight size={12} /></button>)}</nav><main><div className="sg-content relay-content"><header><span>Machines</span><h1>Machines</h1><p>Fleet state, placement, and browser capabilities for your GitSpace account.</p></header><section className="sg-group"><h2>Your machines</h2><div className="sg-card sg-machine-card relay-machine"><span className="sg-card-icon"><Monitor size={19} /></span><span><strong>Darktop</strong><small>local-machine · Physical machine</small><p>Primary development machine · GitSpace browser runtime available in WSL2</p></span><span className="sg-status" data-tone="good">online</span><button>Notes</button></div><div className="relay-browser-card"><div className="relay-browser-head"><span className="relay-browser-icon"><Laptop size={18} /></span><span><strong>Browser Relay</strong><small>Chrome on Darktop · Local relay 127.0.0.1:9224</small></span>{ready ? <Status ready>Ready</Status> : <Status>Setup required</Status>}</div><p>{ready ? 'GitSpace’s Browser Relay extension is loaded in Chrome and connected to the local relay on Darktop. Per-space browser approvals remain required.' : 'Prepare GitSpace Browser Relay on Darktop, load the local extension directory in Chrome, then verify the localhost relay.'}</p><div className="relay-browser-actions">{ready ? <><button className="relay-button">View relay status</button><button className="relay-button" onClick={() => setStep(1)}>Reinstall extension</button></> : <button className="relay-button primary" onClick={() => setStep(1)}><Puzzle size={14} />Set up Browser Relay</button>}</div></div><BrowserRelaySetup step={step} setStep={setStep} onDone={() => setStep(4)} /><div className="sg-card sg-machine-card relay-machine"><span className="sg-card-icon"><Server size={19} /></span><span><strong>Cloudflare build-a</strong><small>Cloud sandbox · cloudflare-sandbox</small><p>Build isolation · no local Chrome browser</p></span><span className="sg-status" data-tone="good">online</span><button>Sleep</button></div><div className="relay-sandbox-note"><strong>Browser Relay is machine-local.</strong> It is unavailable inside managed sandboxes because the extension connects only to localhost on the computer running Chrome and OMP.</div></section></div></main></div></div>;
}
const root = document.getElementById('root'); if (!root) throw new Error('Missing root'); createRoot(root).render(<MachineSettingsMock />);