import assert from 'node:assert/strict';
import { mkdtemp, mkdir, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { chromium, type BrowserContext } from '@playwright/test';
import { Miniflare } from 'miniflare';
import { unzipSync, strFromU8 } from 'fflate';
import { z } from 'zod';
import { RuntimeAccountBrowserPairingSchema, RuntimeAccountBrowserRelayStatusSchema, RuntimeAccountBrowserPlacementSchema, RuntimeToolResultSchema, signRuntimeBrowserAuthorityCertificate, signRuntimeAccountBrowserAuthorization, signRuntimeAccountBrowserGrant, type RuntimeBrowserArguments } from '@gitspace/protocol-runtime';
import { pollUntilReady } from './poll-until-ready.js';

if (process.env.GITSPACE_BROWSER_RELAY_INTEGRATION !== '1' || !process.env.CHROME_PATH) throw new Error('Set GITSPACE_BROWSER_RELAY_INTEGRATION=1 and CHROME_PATH; fixture uses only local workerd and ephemeral Chromium');
const root = await mkdtemp(join(tmpdir(), 'gitspace-account-browser-proof-'));
const compiled = await Bun.build({ entrypoints: [resolve(import.meta.dir, '../../account-worker/test/fixtures/browser-relay-worker.ts')], format: 'esm', target: 'browser', external: ['cloudflare:workers', 'node:*'] });
if (!compiled.success) throw new AggregateError(compiled.logs, 'Fixture worker bundle failed');
const script = await compiled.outputs[0]?.text();
if (!script) throw new Error('Fixture worker bundle missing');
const worker = new Miniflare({ modules: true, script, compatibilityDate: '2026-01-01', compatibilityFlags: ['nodejs_compat'], durableObjects: { RELAY: { className: 'BrowserRelayFixture', useSQLite: true } }, port: 0 });
const address = await worker.ready;
const site = Bun.serve({ hostname: '127.0.0.1', port: 0, fetch: () => new Response('<html><title>Account relay fixture</title><body><h1>Private workspace</h1><input value="private-value"></body></html>', { headers: { 'content-type': 'text/html' } }) });
const accountKeys = await crypto.subtle.generateKey({ name: 'Ed25519' }, true, ['sign', 'verify']);
const workspaceKeys = await crypto.subtle.generateKey({ name: 'Ed25519' }, true, ['sign', 'verify']);
const expiresAt = new Date(Date.now() + 600_000).toISOString();
const trust = { algorithm: 'Ed25519' as const, accountId: 'account', publicKey: Buffer.from(await crypto.subtle.exportKey('raw', accountKeys.publicKey)).toString('base64') };
const authority = await signRuntimeBrowserAuthorityCertificate({ accountId: 'account', projectId: 'project', workspaceId: 'workspace', publicKey: Buffer.from(await crypto.subtle.exportKey('raw', workspaceKeys.publicKey)).toString('base64'), issuedAt: new Date().toISOString(), expiresAt }, accountKeys.privateKey);
const request = async (path: string, value?: unknown) => {
  const response = await fetch(new URL(path, address), value === undefined ? undefined : { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(value) });
  const contentType = response.headers.get('content-type') ?? '';
  if (path !== '/extension.zip' && !contentType.includes('application/json')) throw new Error(`Fixture ${path}: HTTP ${response.status} ${contentType}: ${(await response.text()).slice(0, 3000)}`);
  if (path === '/extension.zip' && !response.ok) throw new Error(`Fixture archive: HTTP ${response.status}: ${(await response.text()).slice(0, 3000)}`);
  return response;
};
const status = async () => RuntimeAccountBrowserRelayStatusSchema.parse(await (await request('/status')).json());
let context: BrowserContext | undefined, secondContext: BrowserContext | undefined;
try {
  const pairing = RuntimeAccountBrowserPairingSchema.parse(await (await request('/pair', trust)).json());
  const archive = unzipSync(new Uint8Array(await (await request('/extension.zip')).arrayBuffer()));
  const extension = join(root, 'extension'); await mkdir(extension);
  for (const [name, bytes] of Object.entries(archive)) { if (name.includes('/') || name.includes('..')) throw new Error('Unsafe fixture archive entry'); await writeFile(join(extension, name), bytes); }
  const manifest = z.object({ host_permissions: z.array(z.string()) }).parse(JSON.parse(strFromU8(archive['manifest.json']!)));
  assert.deepEqual(manifest.host_permissions, [`${address.origin}/*`]);
  context = await chromium.launchPersistentContext(join(root, 'profile'), { executablePath: process.env.CHROME_PATH, headless: true, args: ['--no-sandbox', `--disable-extensions-except=${extension}`, `--load-extension=${extension}`] });
  const extensionWorker = context.serviceWorkers()[0] ?? await context.waitForEvent('serviceworker');
  const extensionId = new URL(extensionWorker.url()).host;
  const popup = await context.newPage(); await popup.goto(`chrome-extension://${extensionId}/popup.html`);
  await popup.locator('#code').fill(JSON.stringify(pairing)); await popup.locator('#pair button').click();
  await pollUntilReady(async () => (await status()).pairings.some(browser => browser.pairingId === pairing.pairingId && browser.connected), { timeoutMs: 15_000, message: 'extension did not connect directly to account worker' });
  const fingerprint = (await status()).pairings.find(browser => browser.pairingId === pairing.pairingId)?.pairedKeyFingerprint; assert.match(fingerprint ?? '', /^[a-f0-9]{64}$/);
  await request('/confirm', { pairingId: pairing.pairingId, fingerprint });
  await request('/project-update', { projectId: 'project', expectedRevision: 0, preferences: { defaultPairingId: pairing.pairingId, approvals: [{ pairingId: pairing.pairingId, name: 'Primary Chrome', note: 'Local smoke fixture' }] } });
  const placement = RuntimeAccountBrowserPlacementSchema.parse(await (await request('/placement', { projectId: 'project' })).json());
  assert.equal(placement.kind, 'account-relay');
  const grant = await signRuntimeAccountBrowserGrant({ projectId: 'project', workspaceId: 'workspace', placement, groupId: crypto.randomUUID(), groupName: 'Account relay fixture', source: 'relay', origins: ['127.0.0.1'], expiresAt }, workspaceKeys.privateKey, authority);
  async function execute(args: RuntimeBrowserArguments, conversationKind: 'main' | 'subagent' = 'main', selectedPlacement = placement, selectedGrant = grant) {
    const id = crypto.randomUUID(), deadlineAt = new Date(Date.now() + 60_000).toISOString();
    const authorization = await signRuntimeAccountBrowserAuthorization({ scope: { projectId: 'project', workspaceId: 'workspace', placement: selectedPlacement, conversationId: 'conversation', conversationKind, taskId: id, requestId: id, attemptId: id }, issuedAt: new Date().toISOString(), expiresAt: deadlineAt, dispatch: { version: 1, tool: 'browser', deadlineAt, replay: 'unsafe' }, command: { type: 'execute', args, grant: selectedGrant } }, workspaceKeys.privateKey, authority);
    return request('/execute', authorization);
  }
  const openedResponse = await execute({ action: 'open', source: 'relay', url: `http://127.0.0.1:${site.port}/` });
  const opened = RuntimeToolResultSchema.parse(await openedResponse.json()); assert.equal(opened.status, 'completed');
  const text = opened.content.find(part => part.type === 'text'); if (!text || text.type !== 'text') throw new Error('Browser did not return target');
  const { targetId } = z.object({ targetId: z.string() }).parse(JSON.parse(text.text));
  const observed = await execute({ action: 'observe', source: 'relay', targetId, offset: 0, limit: 100, screenshot: false });
  assert.equal(observed.status, 200); const observation = JSON.stringify(await observed.json()); assert.ok(!observation.includes('private-value'));
  assert.equal((await execute({ action: 'navigate', source: 'relay', targetId, url: `http://localhost:${site.port}/` })).status, 403);
  assert.equal((await execute({ action: 'tabs', source: 'relay' }, 'subagent')).status, 403);
  if (process.env.GITSPACE_BROWSER_RELAY_SCREENSHOT) await popup.screenshot({ path: process.env.GITSPACE_BROWSER_RELAY_SCREENSHOT });
  await context.close(); context = undefined;
  await pollUntilReady(async () => !(await status()).pairings.some(browser => browser.pairingId === pairing.pairingId && browser.connected), { timeoutMs: 10_000, message: 'closed browser remained connected' });
  context = await chromium.launchPersistentContext(join(root, 'profile'), { executablePath: process.env.CHROME_PATH, headless: true, args: ['--no-sandbox', `--disable-extensions-except=${extension}`, `--load-extension=${extension}`] });
  await pollUntilReady(async () => (await status()).pairings.some(browser => browser.pairingId === pairing.pairingId && browser.connected), { timeoutMs: 15_000, message: 'paired extension did not reconnect' });
  assert.equal((await status()).pairings.find(browser => browser.pairingId === pairing.pairingId)?.pairedKeyFingerprint, fingerprint);
  const secondPairing = RuntimeAccountBrowserPairingSchema.parse(await (await request('/pair', trust)).json());
  secondContext = await chromium.launchPersistentContext(join(root, 'second-profile'), { executablePath: process.env.CHROME_PATH, headless: true, args: ['--no-sandbox', `--disable-extensions-except=${extension}`, `--load-extension=${extension}`] });
  const secondWorker = secondContext.serviceWorkers()[0] ?? await secondContext.waitForEvent('serviceworker');
  const secondPopup = await secondContext.newPage(); await secondPopup.goto(`chrome-extension://${new URL(secondWorker.url()).host}/popup.html`);
  await secondPopup.locator('#code').fill(JSON.stringify(secondPairing)); await secondPopup.locator('#pair button').click();
  await pollUntilReady(async () => (await status()).pairings.some(browser => browser.pairingId === secondPairing.pairingId && browser.connected), { timeoutMs: 15_000, message: 'second independent Chrome did not connect' });
  const secondIdentity = (await status()).pairings.find(browser => browser.pairingId === secondPairing.pairingId);
  assert(secondIdentity?.state === 'pending-confirmation');
  assert.notEqual(secondIdentity.pairedKeyFingerprint, fingerprint);
  await request('/confirm', { pairingId: secondPairing.pairingId, fingerprint: secondIdentity.pairedKeyFingerprint });
  await request('/project-update', { projectId: 'project', expectedRevision: 1, preferences: { defaultPairingId: pairing.pairingId, approvals: [{ pairingId: pairing.pairingId, name: 'Primary Chrome', note: 'Local smoke fixture' }, { pairingId: secondPairing.pairingId, name: 'Second Chrome', note: 'Independent profile' }] } });
  assert.deepEqual(RuntimeAccountBrowserPlacementSchema.parse(await (await request('/placement', { projectId: 'project' })).json()), placement);
  const secondPlacement = RuntimeAccountBrowserPlacementSchema.parse(await (await request('/placement', { projectId: 'project', pairingId: secondPairing.pairingId })).json());
  assert(secondPlacement.kind === 'account-relay');
  assert.equal(secondPlacement.pairingId, secondPairing.pairingId);
  const secondGrant = await signRuntimeAccountBrowserGrant({ projectId: 'project', workspaceId: 'workspace', placement: secondPlacement, groupId: crypto.randomUUID(), groupName: 'Second Chrome fixture', source: 'relay', origins: ['127.0.0.1'], expiresAt }, workspaceKeys.privateKey, authority);
  const secondOpened = RuntimeToolResultSchema.parse(await (await execute({ action: 'open', source: 'relay', url: `http://127.0.0.1:${site.port}/second` }, 'main', secondPlacement, secondGrant)).json());
  assert.equal(secondOpened.status, 'completed');
  const secondText = secondOpened.content.find(part => part.type === 'text'); assert(secondText?.type === 'text');
  const secondTarget = z.object({ targetId: z.string() }).parse(JSON.parse(secondText.text)).targetId;
  assert.notEqual(secondTarget, targetId);
  assert(secondContext.pages().some(page => page.url().endsWith('/second')));
  assert(!context.pages().some(page => page.url().endsWith('/second')));
  assert.equal((await execute({ action: 'observe', source: 'relay', targetId, offset: 0, limit: 100, screenshot: false }, 'main', secondPlacement, secondGrant)).status, 403);
  const revokedOpened = RuntimeToolResultSchema.parse(await (await execute({ action: 'open', source: 'relay', url: `http://127.0.0.1:${site.port}/revoked` })).json());
  assert.equal(revokedOpened.status, 'completed');
  const revokedPage = context.pages().find(page => page.url().endsWith('/revoked'));
  assert(revokedPage, 'The primary Chrome must have a real tab before revocation');
  await request('/project-update', { projectId: 'project', expectedRevision: 2, preferences: { defaultPairingId: secondPairing.pairingId, approvals: [{ pairingId: secondPairing.pairingId, name: 'Second Chrome', note: 'Independent profile' }] } });
  await pollUntilReady(async () => revokedPage.isClosed(), { timeoutMs: 10_000, message: 'Project revocation did not physically close the primary Chrome tab' });
  assert(secondContext.pages().some(page => page.url().endsWith('/second')), 'Project revocation must preserve the sibling Chrome tab');
  assert.equal((await execute({ action: 'tabs', source: 'relay' })).status, 403);
  await request('/unpair', { pairingId: pairing.pairingId });
  const remaining = await status();
  assert.deepEqual(remaining.pairings.map(browser => browser.pairingId), [secondPairing.pairingId]);
  assert.equal((await execute({ action: 'observe', source: 'relay', targetId: secondTarget, offset: 0, limit: 100, screenshot: false }, 'main', secondPlacement, secondGrant)).status, 200);
  await request('/unpair', { pairingId: secondPairing.pairingId }); assert.equal((await status()).pairings.length, 0);
  console.log('Account Chrome relay: two independent Chrome profiles, pending fingerprint confirmation, selection, scoped execution, physical project-revoke closure, sibling isolation, direct worker pairing, redaction, origin/subagent rejection and reconnect passed');
} finally { await secondContext?.close(); await context?.close(); await site.stop(true); await worker.dispose(); await rm(root, { recursive: true, force: true }); }
