#!/usr/bin/env bun
/**
 * Build script for creating standalone GitSpace CLI executables
 *
 * This script:
 * 1. Builds the web app (Vite)
 * 2. Generates an embedded assets module that imports all dist files
 * 3. Compiles everything into a single executable
 * 4. Optionally packages for npm distribution
 *
 * Usage:
 *   bun scripts/build.ts              # Build for current platform
 *   bun scripts/build.ts --all        # Build for all platforms
 *   bun scripts/build.ts --target=linux-x64
 *   bun scripts/build.ts --npm        # Build + create npm packages
 */

import { $ } from "bun";
import { join } from "path";
import { Glob } from "bun";
import { readFileSync, writeFileSync, mkdirSync, copyFileSync, chmodSync } from "fs";

const ROOT = join(import.meta.dir, "..");
const WEB_DIST = join(ROOT, "web/dist");
const EMBEDDED_ASSETS_PATH = join(ROOT, "src/relay/embedded-assets.generated.js");
const VERSION_PATH = join(ROOT, "src/version.generated.ts");
const DIST_DIR = join(ROOT, "dist");
const NPM_DIR = join(ROOT, "npm");

// Read version from package.json
const PKG = JSON.parse(readFileSync(join(ROOT, "package.json"), "utf-8"));
const VERSION = PKG.version;

// Supported targets for cross-compilation
const TARGETS = {
  "darwin-arm64": "bun-darwin-arm64",
  "darwin-x64": "bun-darwin-x64",
  "linux-x64": "bun-linux-x64",
  "linux-arm64": "bun-linux-arm64",
  // "windows-x64": "bun-windows-x64", // Enable when needed
} as const;

type TargetKey = keyof typeof TARGETS;

/** Generate version file with current version */
function generateVersionFile() {
  const code = `/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by: bun scripts/build.ts
 */
export const VERSION = '${VERSION}';
`;
  writeFileSync(VERSION_PATH, code);
  console.log(`✓ Generated version file (${VERSION})`);
}

/** Restore stub file before web build */
function restoreStub() {
  const stub = `/**
 * STUB FILE - Replaced during build
 * Auto-generated by scripts/build.ts
 */
export const EMBEDDED_ASSETS = {};
export function hasEmbeddedAssets() { return false; }
export function getEmbeddedFile(_) { return null; }
`;
  writeFileSync(EMBEDDED_ASSETS_PATH, stub);
}

async function buildWeb() {
  console.log("📦 Building web app...");
  restoreStub(); // Ensure stub is in place before web build
  await $`cd ${join(ROOT, "web")} && bun install && bun run build`;
  console.log("✓ Web app built");
}

async function generateEmbeddedAssets() {
  console.log("🔗 Generating embedded assets module...");

  const glob = new Glob("**/*");
  const files: string[] = [];

  for await (const file of glob.scan({ cwd: WEB_DIST, onlyFiles: true })) {
    files.push(file);
  }

  // Generate imports for each file with { type: "file" } to embed them
  const imports = files.map((file, i) => {
    return `import file${i} from "../../web/dist/${file}" with { type: "file" };`;
  });

  // Generate the assets map: URL path -> embedded file reference
  const assetEntries = files.map((file, i) => `  "/${file}": file${i},`);

  // Also map root to index.html
  const indexIdx = files.findIndex(f => f === "index.html");
  if (indexIdx >= 0) {
    assetEntries.push(`  "/": file${indexIdx},`);
  }

  const code = `/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by: bun scripts/build.ts
 *
 * Embeds web assets for the compiled executable.
 * Types are provided by embedded-assets.generated.d.ts
 */

${imports.join("\n")}

/** URL path -> embedded file path */
export const EMBEDDED_ASSETS = {
${assetEntries.join("\n")}
};

/** True only in compiled binary with embedded files */
export function hasEmbeddedAssets() {
  return typeof Bun !== "undefined" &&
         Array.isArray(Bun.embeddedFiles) &&
         Bun.embeddedFiles.length > 0;
}

/** Get embedded file blob by URL path */
export function getEmbeddedFile(urlPath) {
  const assetPath = EMBEDDED_ASSETS[urlPath];
  if (!assetPath) return null;

  const fileName = String(assetPath).split("/").pop() || "";
  for (const file of Bun.embeddedFiles) {
    if (file.name.endsWith(fileName)) {
      return file;
    }
  }
  return null;
}
`;

  await Bun.write(EMBEDDED_ASSETS_PATH, code);
  console.log(`✓ Generated embedded assets (${files.length} files)`);
}

async function compile(target?: TargetKey) {
  const targetFlag = target ? `--target=${TARGETS[target]}` : "";
  const outName = target ? `gssh-${target}` : "gssh";
  const outFile = join(DIST_DIR, outName);

  console.log(`🔨 Compiling${target ? ` for ${target}` : ""}...`);

  await $`mkdir -p ${DIST_DIR}`;

  const args = [
    "bun", "build",
    "--compile",
    "--minify",
    `--outfile=${outFile}`,
    targetFlag,
    join(ROOT, "src/index.ts"),
  ].filter(Boolean);

  await $`${args}`;

  const stat = await Bun.file(outFile).stat();
  const sizeMB = (stat?.size || 0) / 1024 / 1024;

  console.log(`✓ Built ${outFile} (${sizeMB.toFixed(1)} MB)`);
  return outFile;
}

/**
 * Create npm package for a specific platform
 */
async function createPlatformPackage(target: TargetKey) {
  const pkgName = `@gitspace/${target}`;
  const pkgDir = join(NPM_DIR, target);
  const binDir = join(pkgDir, "bin");

  console.log(`📦 Creating npm package: ${pkgName}`);

  mkdirSync(binDir, { recursive: true });

  // Copy binary
  const binaryPath = join(DIST_DIR, `gssh-${target}`);
  const destPath = join(binDir, "gssh");
  copyFileSync(binaryPath, destPath);
  chmodSync(destPath, 0o755);

  // Create package.json
  const pkg = {
    name: pkgName,
    version: VERSION,
    description: `GitSpace CLI binary for ${target}`,
    os: [target.startsWith("darwin") ? "darwin" : "linux"],
    cpu: [target.endsWith("arm64") ? "arm64" : "x64"],
    bin: {
      [`gssh-${target}`]: "bin/gssh"
    },
    repository: {
      type: "git",
      url: "https://github.com/inkibra/gitspace.sh.git"
    },
    homepage: "https://gitspace.sh",
    license: "SEE LICENSE IN LICENSE"
  };

  writeFileSync(join(pkgDir, "package.json"), JSON.stringify(pkg, null, 2));
  console.log(`✓ Created ${pkgDir}`);
}

/**
 * Update main package.json optionalDependencies versions
 */
function updateMainPackage() {
  const mainPkgPath = join(ROOT, "package.json");
  const pkg = JSON.parse(readFileSync(mainPkgPath, "utf-8"));

  // Update optional dependencies versions to match current version
  if (pkg.optionalDependencies) {
    for (const dep of Object.keys(pkg.optionalDependencies)) {
      pkg.optionalDependencies[dep] = VERSION;
    }
    writeFileSync(mainPkgPath, JSON.stringify(pkg, null, 2) + "\n");
    console.log(`✓ Updated optionalDependencies to v${VERSION}`);
  }
}

/** Get current platform target key */
function getCurrentTarget(): TargetKey {
  const platform = process.platform;
  const arch = process.arch;

  if (platform === "darwin" && arch === "arm64") return "darwin-arm64";
  if (platform === "darwin" && arch === "x64") return "darwin-x64";
  if (platform === "linux" && arch === "x64") return "linux-x64";
  if (platform === "linux" && arch === "arm64") return "linux-arm64";

  throw new Error(`Unsupported platform: ${platform}-${arch}`);
}

async function main() {
  const args = process.argv.slice(2);
  const buildAll = args.includes("--all");
  const buildNpm = args.includes("--npm");
  const targetArg = args.find(a => a.startsWith("--target="));
  const target = targetArg?.split("=")[1] as TargetKey | undefined;

  console.log(`🚀 GitSpace CLI Build v${VERSION}\n`);

  generateVersionFile();
  await buildWeb();
  await generateEmbeddedAssets();

  // Determine which targets to build
  let targetsToBuild: TargetKey[];

  if (buildAll) {
    targetsToBuild = Object.keys(TARGETS) as TargetKey[];
  } else if (target) {
    if (!(target in TARGETS)) {
      console.error(`Unknown target: ${target}`);
      console.error(`Available: ${Object.keys(TARGETS).join(", ")}`);
      process.exit(1);
    }
    targetsToBuild = [target];
  } else {
    // Default: just current platform
    targetsToBuild = [getCurrentTarget()];
  }

  // Build binaries
  console.log(`\n📦 Building for: ${targetsToBuild.join(", ")}...\n`);
  for (const t of targetsToBuild) {
    await compile(t);
  }

  // Create npm packages if requested
  if (buildNpm) {
    console.log("\n📦 Creating npm packages...\n");
    for (const t of targetsToBuild) {
      await createPlatformPackage(t);
    }
    updateMainPackage();
  }

  console.log("\n✅ Build complete!");

  if (buildNpm) {
    console.log("\n📋 To publish to npm:");
    console.log("   npm publish  # main package (gitspace)");
    for (const t of targetsToBuild) {
      console.log(`   cd npm/${t} && npm publish --access public`);
    }
  }
}

main().catch(e => {
  console.error("Build failed:", e);
  process.exit(1);
});
