#!/usr/bin/env bun
/**
 * Writes `src/version.generated.ts`.
 *
 * The file is gitignored, so a fresh checkout does not have it, and
 * `src/lib/tmux-lite/protocol.ts` imports it — which means typecheck and the
 * test suite both fail on a clean clone until it exists. It used to be written
 * only by `scripts/build.ts`, so every developer had one lying around as build
 * residue and nobody noticed; CI, which never builds, failed 48 of 256 test
 * files on the missing module.
 *
 * Hence a standalone generator, invoked by `typecheck` and `test` as well as
 * the build. Cheap enough to run unconditionally.
 */
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = join(import.meta.dir, '..');
const VERSION_PATH = join(ROOT, 'src/version.generated.ts');

/**
 * Commit sha, marked `-dirty.<ms>` when the tree has uncommitted changes so two
 * builds from the same commit are still distinguishable.
 */
function computeBuildId(): string {
  try {
    const sha = execFileSync('git', ['rev-parse', '--short', 'HEAD'], { cwd: ROOT }).toString().trim();
    const dirty = execFileSync('git', ['status', '--porcelain'], { cwd: ROOT }).toString().trim().length > 0;
    return dirty ? `${sha}-dirty.${Date.now()}` : sha;
  } catch {
    // Not a git checkout (e.g. building from a tarball) — fall back to build time.
    return `build.${Date.now()}`;
  }
}

/** Generate the version file from package.json + the current build id. */
export function generateVersionFile(): void {
  const pkg: unknown = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf-8'));
  const version = typeof pkg === 'object' && pkg !== null && 'version' in pkg ? String(pkg.version) : '0.0.0';
  const buildId = computeBuildId();
  writeFileSync(
    VERSION_PATH,
    `/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by: bun scripts/gen-version.ts
 */
export const VERSION = '${version}';
export const BUILD_ID = '${buildId}';
`,
  );
  console.log(`✓ Generated version file (${version} / ${buildId})`);
}

if (import.meta.main) generateVersionFile();
