#!/usr/bin/env bun
/**
 * Writes `src/cloud/bootstrap-bundle.generated.js`.
 *
 * Same trap as `gen-version.ts`: gitignored, previously written only by
 * `scripts/build.ts`, and therefore present on every developer machine as build
 * residue but absent on CI and in fresh clones. Without it `cloudLaunch` gets a
 * null bundle and fails with "Bundle failed", which is a missing build artifact
 * wearing the costume of a product bug.
 *
 * A stub with an empty payload would satisfy the import but still return null,
 * so this builds the real bundle — it is a single self-contained entrypoint
 * with no web assets involved, and cheap enough to run before the suite.
 */
import { existsSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = join(import.meta.dir, '..');
const ENTRY = join(ROOT, 'src/cloud/bootstrap-entry.ts');
const OUT = join(ROOT, 'src/cloud/bootstrap-bundle.generated.js');

export async function generateCloudBootstrapBundle(): Promise<void> {
  if (!existsSync(ENTRY)) throw new Error(`Missing cloud bootstrap entrypoint: ${ENTRY}`);

  const result = await Bun.build({
    entrypoints: [ENTRY],
    target: 'bun',
    // OMP's legacy-pi-compat does a conditional `import("omp-legacy-pi-modules")`
    // for a package that is not installed and is not meant to be. Bundling it is
    // impossible; leaving it external preserves today's runtime behaviour, where
    // that dynamic import simply fails and the legacy path stays off.
    external: ['omp-legacy-pi-modules'],
    format: 'esm',
    minify: true,
    splitting: false,
    sourcemap: 'none',
  });

  if (!result.success || result.outputs.length === 0) {
    const messages = result.logs.map((log) => log.message).join('\n');
    throw new Error(`Failed to build cloud bootstrap bundle${messages ? `:\n${messages}` : ''}`);
  }

  const base64 = Buffer.from(await result.outputs[0]!.text(), 'utf-8').toString('base64');
  writeFileSync(
    OUT,
    `/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by: bun scripts/gen-cloud-bootstrap.ts
 */
export const CLOUD_BOOTSTRAP_BUNDLE_BASE64 = '${base64}';
export const CLOUD_BOOTSTRAP_BUNDLE_FILENAME = 'gssh-cloud-bootstrap.mjs';

export function getCloudBootstrapBundleSource() {
  if (!CLOUD_BOOTSTRAP_BUNDLE_BASE64) {
    return null;
  }
  return Buffer.from(CLOUD_BOOTSTRAP_BUNDLE_BASE64, 'base64').toString('utf-8');
}
`,
  );
  console.log('✓ Generated cloud bootstrap bundle');
}

if (import.meta.main) await generateCloudBootstrapBundle();
