import React from 'react';
import {
  AbsoluteFill,
  Audio,
  Sequence,
  staticFile,
  useCurrentFrame,
  interpolate,
  Easing,
} from 'remotion';
import { loadFont } from '@remotion/google-fonts/JetBrainsMono';
// NOTE: no VO track yet — the real recording lands here later.
import { T } from '../../lib/theme';
import { TL, DECK, ACTS } from './timeline';
import { PrWall } from './scenes/PrWall';
import { GuideBeats } from './scenes/GuideBeats';
import { Deck, EndCard, TAGLINE, STINGER } from './Deck';
import { KineticCaptions, type CapLine } from '../../lib/Captions';
import { FaultyTerminalFrame } from '../../lib/FaultyTerminalFrame';
import { ParticleScrollFrame } from '../../lib/ParticleScrollFrame';
import { BendFrame } from '../../lib/BendFrame';
import { Cursor } from '../../lib/ui';

loadFont();

const P = DECK.matchCut; // product-local offset (5s dust intro)
const CAP_SHIFT = 90; // captions live in (global − 90), same convention as ep02
const ease = Easing.inOut(Easing.cubic);
const clamp = { extrapolateLeft: 'clamp', extrapolateRight: 'clamp' } as const;

const A = T.waiting; // agent — the PR byline's blue
const G = T.accent; // the green things: beat badges, ✓ reviewed
const D = T.error; // the lie: alphabetical order's red dependency
const AM = T.needsInput; // the journal card's amber

/** Frames where typed() reveals a new character (mirrors ui.typed math). */
const typingFrames = (start: number, cps: number, chars: number): number[] => {
  const frames: number[] = [];
  let prev = 0;
  for (let f = start; prev < chars && f < start + 400; f++) {
    const n = Math.min(chars, Math.max(0, Math.floor((f - start) * cps)));
    if (n > prev) frames.push(f);
    prev = n;
  }
  return frames;
};
const everyThird = (frames: number[]): number[] =>
  frames.filter((_, i) => i % 3 === 0 || i === frames.length - 1);
const TAG_KEYS = everyThird(typingFrames(DECK.tagType, 1.35, TAGLINE.length));
const STING_KEYS = everyThird(typingFrames(DECK.stingerType, 1.35, STINGER.length));

/**
 * Captions generated by the ep03 prosody solver (/tmp/solve03.mjs +
 * /tmp/gen03.mjs): syllable-timed words, punctuation pauses, 32-frame breaths,
 * and every line opening AFTER the thing it reacts to. Past tense through the
 * stall, present from the turn. Colour only names what is on screen.
 */
const MAIN_CAPTIONS: CapLine[] = [
  {
    // the PR lands; `agent` is blue because the PR byline is
    y: 872, size: 44, out: 200,
    words: [
      { w: 'The', at: 89 }, { w: 'agent', at: 97, color: A }, { w: 'opened', at: 110 }, { w: 'a', at: 128 },
      { w: 'PR.', at: 136 }, { w: 'Fourteen', at: 156 }, { w: 'files.', at: 169 },
    ],
  },
  {
    // reacting to the crawl starting
    y: 872, size: 46, out: 341,
    words: [
      { w: 'I', at: 226 }, { w: 'read', at: 234 }, { w: 'it', at: 242 }, { w: 'like', at: 250 },
      { w: 'we', at: 258 }, { w: 'all', at: 266 }, { w: 'do.', at: 274 }, { w: 'Top', at: 294 },
      { w: 'to', at: 302 }, { w: 'bottom.', at: 310 },
    ],
  },
  {
    // the stall. `first`/`last` red — the red dependency line is on screen.
    y: 866, size: 44, out: 479,
    words: [
      { w: 'Oh.', at: 367 }, { w: 'The', at: 387 }, { w: 'first', at: 395, color: D }, { w: 'file', at: 403 },
      { w: 'meant', at: 411 }, { w: 'nothing', at: 419 }, { w: 'without', at: 432 }, { w: 'the', at: 445 },
      { w: 'last.', at: 453, color: D },
    ],
  },
  {
    // the turn — opens ON the bend
    y: 866, size: 44, out: 596,
    words: [
      { w: "I'll", at: 505 }, { w: 'need', at: 513 }, { w: 'the', at: 521 }, { w: 'story,', at: 529 },
      { w: 'not', at: 549 }, { w: 'the', at: 557 }, { w: 'pages.', at: 565 },
    ],
  },
  {
    // reacting to the rows flying into build order
    y: 872, size: 44, out: 808,
    words: [
      { w: 'Now', at: 688 }, { w: 'the', at: 696 }, { w: 'analyzer', at: 704 }, { w: 'computes', at: 727 },
      { w: 'the', at: 745 }, { w: 'order', at: 753 }, { w: 'it', at: 766 }, { w: 'was', at: 774 },
      { w: 'built.', at: 782, underline: true },
    ],
  },
  {
    // `beats.` green as the badges land
    y: 872, size: 46, out: 906,
    words: [
      { w: 'Fourteen', at: 834 }, { w: 'files.', at: 847 }, { w: 'Four', at: 872 }, { w: 'beats.', at: 880, color: G },
    ],
  },
  {
    // `journal,` amber — the amber quote card is on screen
    y: 872, size: 42, out: 1049,
    words: [
      { w: 'Each', at: 932 }, { w: 'beat', at: 940 }, { w: 'quotes', at: 948 }, { w: 'the', at: 961 },
      { w: 'journal,', at: 969, color: AM }, { w: 'written', at: 989 }, { w: 'before', at: 1002 }, { w: 'the', at: 1015 },
      { w: 'code.', at: 1023 },
    ],
  },
  {
    // the beats checking off, named in order
    y: 872, size: 46, out: 1182,
    words: [
      { w: 'Foundations.', at: 1075 }, { w: 'Then', at: 1105 }, { w: 'wiring.', at: 1113 }, { w: 'Then', at: 1138 },
      { w: 'surfaces.', at: 1146 },
    ],
  },
  {
    // the payoff; `review` green under the ✓ reviewed stamp
    y: 872, size: 46, out: 1287,
    words: [
      { w: 'This', at: 1208 }, { w: 'is', at: 1216 }, { w: 'a', at: 1224 }, { w: 'review', at: 1232, color: G },
      { w: 'I', at: 1245 }, { w: 'can', at: 1253 }, { w: 'start.', at: 1261 },
    ],
  },
];

const VO_SEGMENTS: Array<[number, number]> = [
  [89, 194], [226, 335], [367, 473], [505, 590], [688, 802], [834, 900], [932, 1043], [1075, 1176], [1208, 1281],
];
const padDuck = (f: number): number => {
  for (const [a, b] of VO_SEGMENTS) {
    if (f >= a - 10 && f <= b + 16) {
      const in_ = Math.min(1, Math.max(0, (f - (a - 10)) / 10));
      const out_ = Math.min(1, Math.max(0, ((b + 16) - f) / 16));
      return 0.85 - 0.22 * Math.min(in_, out_);
    }
  }
  return 0.85;
};

/** The turn between pages and story — the one bend in the film. */
const TURN = {
  zone: 620,
  angle: 86,
  rounding: 260,
  perspective: 900,
  direction: 'in',
  ease: 620,
  smoothing: 0,
  transparent: true,
  top: true,
  bottom: true,
  tumble: 0,
  tilt: 0,
} as const;

/** Fine dark grain for the ending — the type erodes, not explodes. */
const SAND_OUT = {
  band: 700,
  density: 2.2,
  size: 1.5,
  spread: 210,
  gravity: 0.45,
  drift: 1,
  swirl: 150,
  stagger: 0.6,
  fade: 0.9,
  settle: 0.3,
  smoothing: 0,
  transparent: true,
} as const;

/** The product story, in product-local frames (pf). */
const Product: React.FC<{ pf: number }> = ({ pf }) => {
  const turning = pf >= TL.openSlideStart && pf < TL.openSlideEnd;
  const turn = interpolate(pf, [TL.openSlideStart, TL.openSlideEnd], [0, 1], { ...clamp, easing: ease });
  const showWall = pf < TL.openSlideStart;
  const showGuide = pf >= TL.openSlideEnd;

  // the human's hand: cursor + click punch on the two acts only (ep01's envelope)
  let punch = 0;
  let punchAt = { x: 960, y: 540 };
  let cursorOp = 0;
  let cx = 960;
  let cy = 540;
  let click = 0;
  for (let i = 0; i < ACTS.length; i++) {
    const a = ACTS[i]!;
    const d = pf - a.at;
    if (d >= -26 && d <= 26) {
      const from = i > 0 ? ACTS[i - 1]! : { x: 1480, y: 320 };
      const travel = interpolate(pf, [a.at - 26, a.at - 2], [0, 1], { ...clamp, easing: ease });
      cx = from.x + (a.x - from.x) * travel;
      cy = from.y + (a.y - from.y) * travel;
      cursorOp =
        interpolate(pf, [a.at - 26, a.at - 18], [0, 1], clamp) *
        interpolate(pf, [a.at + 12, a.at + 24], [1, 0], clamp);
      click = interpolate(pf, [a.at, a.at + 12], [1, 0], clamp);
    }
    if (d >= 0 && d <= 28) {
      punch =
        d < 3 ? Easing.out(Easing.cubic)(d / 3)
        : d < 8 ? 1
        : 1 - Easing.inOut(Easing.cubic)((d - 8) / 20);
      punchAt = { x: a.x, y: a.y };
    }
  }
  const punchScale = 1 + 0.028 * punch;

  return (
    <AbsoluteFill
      style={{
        background: T.bg,
        transform: `scale(${punchScale})`,
        transformOrigin: `${punchAt.x}px ${punchAt.y}px`,
      }}
    >
      {/* the site's hero field — 0.22, the measured video value, not the web's 0.12 */}
      <FaultyTerminalFrame width={1920} height={1080} opacity={0.22} />

      {showWall && <PrWall frame={pf} />}

      {/* THE TURN — pages fold away, the story unfolds. One sheet. */}
      {turning && (
        <BendFrame position={turn} options={TURN}>
          <PrWall frame={pf} />
          <GuideBeats frame={pf} />
        </BendFrame>
      )}

      {showGuide && <GuideBeats frame={pf} />}

      {cursorOp > 0.001 && (
        <div style={{ opacity: cursorOp }}>
          <Cursor x={cx} y={cy} click={click} />
        </div>
      )}
    </AbsoluteFill>
  );
};

export const ChangeGuide: React.FC = () => {
  const frame = useCurrentFrame();
  const pf = frame - P;
  const inDeck = frame < P || frame >= DECK.outStart;
  const sanding = frame >= DECK.sandStart;
  const product = <Product pf={pf} />;

  return (
    <AbsoluteFill style={{ background: T.bg }}>
      {/* ── soundtrack ── */}
      <Audio
        src={staticFile('audio/pad-long.wav')}
        volume={(f) => padDuck(f - CAP_SHIFT) * interpolate(f, [DECK.total - 70, DECK.total - 8], [1, 0], clamp)}
      />
      <Audio src={staticFile('audio/riser.wav')} volume={0.8} />
      <Sequence from={DECK.select}>
        <Audio src={staticFile('audio/thunk.wav')} volume={0.8} />
      </Sequence>
      {/* the stall — the lie surfaces (amber droplet, like ep02's crack) */}
      <Sequence from={TL.stall + P}>
        <Audio src={staticFile('audio/droplet-amber.wav')} volume={0.7} />
      </Sequence>
      {/* the two clicks */}
      {ACTS.map((a) => (
        <Sequence key={`click-${a.at}`} from={a.at + P}>
          <Audio src={staticFile('audio/click.wav')} volume={0.75} />
        </Sequence>
      ))}
      {/* the turn */}
      <Sequence from={TL.openSlideStart + P}>
        <Audio src={staticFile('audio/whoosh.wav')} volume={0.55} />
      </Sequence>
      {/* badges land */}
      <Sequence from={TL.badges + P}>
        <Audio src={staticFile('audio/bloom-flags.wav')} volume={0.6} />
      </Sequence>
      {/* first beat checks off, then the stamp */}
      <Sequence from={TL.checks + P}>
        <Audio src={staticFile('audio/bloom-docs.wav')} volume={0.62} />
      </Sequence>
      <Sequence from={TL.stamp + P}>
        <Audio src={staticFile('audio/sparkle.wav')} volume={0.55} />
      </Sequence>
      <Sequence from={DECK.outStart}>
        <Audio src={staticFile('audio/whoosh.wav')} volume={0.55} />
      </Sequence>
      <Sequence from={DECK.deckBack}>
        <Audio src={staticFile('audio/sparkle.wav')} volume={0.5} />
      </Sequence>
      {[...TAG_KEYS, ...STING_KEYS].map((at, i) => (
        <Sequence key={`tagkey-${at}-${i}`} from={at}>
          <Audio src={staticFile(`audio/key-${((i + 2) % 4) + 1}.wav`)} volume={0.26} />
        </Sequence>
      ))}

      {/* ── one snippet in a deck of snippets ── */}
      {inDeck ? <Deck frame={frame} hideType={sanding}>{product}</Deck> : product}

      {/* ── the ending: the type erodes into sand ── */}
      {sanding && (
        <>
          <AbsoluteFill
            style={{ background: '#000', opacity: interpolate(frame, [DECK.sandStart, DECK.sandStart + 30], [0, 1], clamp) }}
          />
          <ParticleScrollFrame
            progress={interpolate(frame, [DECK.sandStart, DECK.sandEnd], [1, 0], { ...clamp, easing: Easing.in(Easing.quad) })}
            options={SAND_OUT}
          >
            <EndCard frame={frame} />
          </ParticleScrollFrame>
        </>
      )}

      {/* ── VO captions (placeholder timings; retime to the recording) ── */}
      <KineticCaptions frame={frame - CAP_SHIFT} lines={MAIN_CAPTIONS} />
    </AbsoluteFill>
  );
};
