// AUTO-GENERATED by scripts/build.ts — DO NOT EDIT
// Embeds the pi-natives .node addon for linux-x64 into the compiled binary.
// In dev mode this file is a complete no-op; the import of the .node asset is
// deferred behind the isCompiled guard so Bun never tries to ESM-load a native
// addon at module evaluation time.
import { mkdirSync, existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import * as os from "node:os";

const isCompiled =
  import.meta.url.includes("$bunfs") ||
  import.meta.url.includes("~BUN") ||
  import.meta.url.includes("%7EBUN");

if (isCompiled) {
  // Dynamic import: the `with { type: "file" }` attribute tells Bun's bundler
  // to embed the .node binary as an asset and return its extracted path at
  // runtime. This import MUST stay inside the isCompiled guard because in dev
  // mode Bun cannot ESM-import a Node-API .node file.
  // @ts-ignore -- .node module resolved by Bun bundler at compile time; no declaration exists in dev
  const { default: addonPath } = await import("../node_modules/@oh-my-pi/pi-natives/native/pi_natives.linux-x64-baseline.node");
  const dir = join(os.homedir(), ".omp", "natives", "14.7.3");
  const target = join(dir, "pi_natives.linux-x64-baseline.node");
  if (!existsSync(target)) {
    try {
      mkdirSync(dir, { recursive: true });
      writeFileSync(target, readFileSync(addonPath));
    } catch {
      // Best-effort: pi-natives will report its own error if this fails.
    }
  }
}
