// AUTO-GENERATED by scripts/build.ts — DO NOT EDIT
// Embeds the pi-natives .node addon for darwin-arm64 into the compiled binary.
import addonPath from "../node_modules/@oh-my-pi/pi-natives/native/pi_natives.darwin-arm64.node" with { type: "file" };
import { mkdirSync, existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import * as os from "node:os";

const isCompiled =
  import.meta.url.includes("$bunfs") ||
  import.meta.url.includes("~BUN") ||
  import.meta.url.includes("%7EBUN");

if (isCompiled) {
  const dir = join(os.homedir(), ".omp", "natives", "13.17.5");
  const target = join(dir, "pi_natives.darwin-arm64.node");
  if (!existsSync(target)) {
    try {
      mkdirSync(dir, { recursive: true });
      writeFileSync(target, readFileSync(addonPath));
    } catch {
      // Best-effort: pi-natives will report its own error if this fails.
    }
  }
}
