/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false` (hash: 662b13825e9f1452bc9db14fc3495a82)
interface __BaseEnv_Env {
	AUTH_PUBLIC_KEY: "replace-with-base64-ed25519-public-key";
	RELAY_NAME: "default";
	AUTH_MAX_SKEW_MS: 60000;
	TUNNEL_HEADER_TIMEOUT_MS: 10000;
	TUNNEL_IDLE_TIMEOUT_MS: 30000;
	RELAY: DurableObjectNamespace<import("./src/index").UserRelayDO>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "UserRelayDO";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AUTH_PUBLIC_KEY" | "RELAY_NAME" | "AUTH_MAX_SKEW_MS" | "TUNNEL_HEADER_TIMEOUT_MS" | "TUNNEL_IDLE_TIMEOUT_MS">> {}
}
